## Importing numpy library and doing basic array operations

In [2]:
import numpy as np

In [1]:
a = np.array([10,20,30])  # this is one dimensional
print(a)

[10 20 30]


In [2]:
print(a.dtype)   # printing datatype

int32


In [3]:
print(a.ndim)   # printing dimension

1


In [4]:
a = np.array( [ [10,20], [30,40] ] ) # initializing two dimensional array
print(a)
print(a.ndim)

[[10 20]
 [30 40]]
2


In [5]:
print(a.itemsize)  # printing the size of the elements of the array

4


In [6]:
a = np.array( a, dtype = np.float64 )  # changing datatype of the elements
print(a)
print(a.itemsize)  # float is 8 bytes

[[10. 20.]
 [30. 40.]]
8


In [15]:
# Homogeneous array with elements of different types
arr1 = np.array([1, 2.5, 3])
print(arr1.dtype)  # Result: float64 (all elements are promoted to float)

# Structured array with elements of different types
arr2 = np.array([('Alice', 25), ('Bob', 30)], dtype=[('name', 'U10'), ('age', int)])
print(arr2.dtype)  # Result: [('name', '<U10'), ('age', '<i8')]

float64
[('name', '<U10'), ('age', '<i4')]


In [ ]:
''' Yes, NumPy arrays can indeed contain elements of multiple data types. However, there are a few important points to consider:

Homogeneous vs. Heterogeneous Arrays:

By default, NumPy arrays are homogeneous, meaning all elements in the array have the same data type. This is efficient for numerical computations because NumPy can optimize memory usage and computation speed.
If you attempt to create an array with elements of different data types, NumPy will automatically promote all elements to a common data type, resulting in a homogeneous array.
Structured Arrays:

NumPy also provides structured arrays, which allow you to define arrays with elements of different data types in a structured way, similar to a database table or a spreadsheet.
Structured arrays are useful for handling heterogeneous data, such as structured datasets with different types of information (e.g., names, ages, and heights).
Here's a brief example of how you can create arrays with elements of multiple data types:
In this example:

arr1 is a homogeneous array with elements [1, 2.5, 3]. Since it contains both integers and floats, NumPy automatically promotes all elements to the common data type float64.
arr2 is a structured array with elements [(Alice, 25), (Bob, 30)]. The dtype parameter specifies the data types of the structured array's fields. In this case, 'U10' represents Unicode strings of maximum length 10 (name), and int represents integers (age).'''

In [7]:
print(a.size)
print(a[0])
print(a[0][0])
print(a[1][1])

4
[10. 20.]
10.0
40.0


In [8]:
print(a.shape)

(2, 2)


In [9]:
a = np.array([ [10,20], [30,40], [50,60] ])
print(a)
print(a.shape)    # shape prints the row-column

[[10 20]
 [30 40]
 [50 60]]
(3, 2)


In [15]:
# these methods don't actually change anything in the array, it just display as we want
print(a.reshape(1,6))  # using reshape method we can reshape the row column as we want but it have to fit into that
print(a)
print(a.ravel())  # ravel prints any type of array into one dimensional array
print(a)

[[10 20 30 40 50 60]]
[[10 20]
 [30 40]
 [50 60]]
[10 20 30 40 50 60]
[[10 20]
 [30 40]
 [50 60]]


In [11]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [10]:
a = np.zeros( (3,2) )   
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
a = np.ones( (3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
a = np.arange(1,5)   # arange method works just like the range function in list
print(a)

[1 2 3 4]


In [13]:
a = np.arange(1,5,2) # the third parameter is the increament value since start value
print(a)

[1 3]


In [14]:
a = np.linspace(1,5,20)  # linspace create a set of (third parameter) numbers equally divided in the range from start to end 
print(a)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [29]:
# other important methods
a = np.array([ [10,20], [30,40], [50,60] ])
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
b = np.array([ [1,2], [3,4], [5,6] ])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

10
60
210
[ 90 120]
[ 30  70 110]
[[11 22]
 [33 44]
 [55 66]]
[[ 9 18]
 [27 36]
 [45 54]]
[[ 10  40]
 [ 90 160]
 [250 360]]
[[10. 10.]
 [10. 10.]
 [10. 10.]]


In [31]:
b = np.array([ [1,2], [3,4] ])
print(a.dot(b))

[[ 70 100]
 [150 220]
 [230 340]]


## Indexing

In [17]:
list_1 = [1, 2, 3, 4]
list_2 = [3, 4, 5, 6]
list_3 = [5, 6, 7 ,8]
a = np.array([list_1, list_2, list_3])
print(a)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


In [33]:
print(a[:,:])

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


In [34]:
print(a[0:2,:])

[[1 2 3 4]
 [3 4 5 6]]


In [35]:
print(a[0:2,1:])

[[2 3 4]
 [4 5 6]]


In [28]:
print(a[::-1])  # reversing an array

[[5 6 7 8]
 [3 4 5 6]
 [1 2 3 4]]


## Copying an array

In [55]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr_1)
arr_2 = arr_1
arr_2[2:] = 500
print(arr_2)
print(arr_1)   # copying in a normal way can cause this issue because in this way they both share the same memory space

[1 2 3 4 5 6 7 8 9]
[  1   2 500 500 500 500 500 500 500]
[  1   2 500 500 500 500 500 500 500]


In [56]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr_1)
arr_2 = arr_1.copy()  # this is the solution
arr_2[2:] = 500
print(arr_2)
print(arr_1)

[1 2 3 4 5 6 7 8 9]
[  1   2 500 500 500 500 500 500 500]
[1 2 3 4 5 6 7 8 9]


## Stacking

In [29]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [30]:
print(np.vstack((a,b)))
c = np.hstack((a,b))
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


## Splitting

In [34]:
print(c)
result = np.hsplit(c,2)
print(type(result))
print(result[0])
print(result[1])
result = np.vsplit(c,3)
print(result[0])

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]
<class 'list'>
[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[0 1 6 7]]


## Indexing with boolean arrays

In [57]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
b = a > 4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [59]:
print(a[b])

[ 5  6  7  8  9 10 11]


In [60]:
a[b] = -1
print(a)

[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
